---
- name: check current timezone
  command: diff -s /etc/localtime /usr/share/zoneinfo/{{ timezone }}
  register: diff_output
  changed_when: "diff_output.rc == 1"
  failed_when: False

- name: set localtime
  file:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
  when: diff_output.rc == 1

- name: set timezone
  copy: >
    content='{{ timezone }}{{ '\n' }}'
    dest=/etc/timezone
  when: diff_output.rc == 1

- name: update timezone
  command: >
    dpkg-reconfigure --frontend noninteractive tzdata
  when: diff_output.rc == 1
